### ISSUE TITLE
The performance of the model

### ISSUE THREAD

**Issue by jiangix01** [chan0park/long-summarization#1]
Hello,
    Thanks for your great work. I have run the code following the 'readme'. However, the performance of the model is not good, I can not get the similar performance as the official tensorflow code "https://github.com/armancohan/long-summarization". And what can i do for that? Thanks a lot.

**Comment by chan0park** [comment]
Hello,

I and my teammates worked on this project as a course project, and could not match the number in the paper.  So what you are seeing from the results is expected and this repository will be removed soon. 
However, we managed to match the number in the paper by building upon the [Pytorch code of pointer generator network](https://github.com/atulkum/pointer_summarizer), so I suggest you starting from their code. 

Thanks,
Chan
